services:
  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: eshop

    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  web:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - database

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      # PLACEHOLDER JWT SECRET
      JWT_SECRET: secret
    depends_on:
      - database
