version: '3'

services:
  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: eshop

    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  web:
    build: ..
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - database
