name: Build and Deploy

on:
  push:
    branches:
      - github_actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: |
          ~/.bun/bin/bun install && ~/.bun/bin/bun run build

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.SERVER_SSH_KEY }}")
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_HOST }} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINPzy2WhfsFmYpQFh55Nlh8q0ywmgT5jWjiIgbwSXyZT adam.virostek@gmail.com" >> ~/.ssh/known_hosts

      - name: Copy files
        run: |
          rsync -avz --exclude 'node_modules' -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/viro/web

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/viro/web/docker
            docker compose down
            docker compose up --build -d
